# Generated by Django 5.1.3 on 2025-01-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_pivotmodel_rolemodel_pivotmodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='pivot',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.rolemodel'),
        ),
        migrations.DeleteModel(
            name='Pivot',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
