# Generated by Django 5.1.3 on 2025-01-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('currency', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('iso_3166_2', models.CharField(max_length=2)),
                ('iso_3166_3', models.CharField(max_length=3)),
                ('calling_code', models.CharField(max_length=10)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'CountryModel',
                'verbose_name_plural': 'CountryModels',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.countrymodel')),
            ],
            options={
                'verbose_name': 'StateModel',
                'verbose_name_plural': 'StateModels',
                'db_table': 'State',
            },
        ),
    ]
