# Generated by Django 5.1.3 on 2025-01-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pivot_role_pivot_role_alter_user_role'),
        ('core', '0002_pivotmodel_rolemodel_pivotmodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='pivot',
        ),
        migrations.DeleteModel(
            name='PivotModel',
        ),
        migrations.DeleteModel(
            name='RoleModel',
        ),
    ]
