# Generated by Django 5.1.3 on 2025-01-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='uantity',
            new_name='quantity',
        ),
    ]
