# Generated by Django 5.1.3 on 2025-01-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_uantity_cartmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='variations',
            new_name='variation',
        ),
    ]
