# Generated by Django 5.1.3 on 2025-01-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_variations_cartmodel_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsmodel',
            old_name='user',
            new_name='consumer',
        ),
    ]
