# Generated by Django 5.1.3 on 2025-01-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_categorymodel_tagsmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=50)),
                ('disk', models.CharField(default='public', max_length=50)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField()),
            ],
            options={
                'verbose_name': 'ImageModel',
                'verbose_name_plural': 'ImageModel',
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('descriptions', models.TextField()),
                ('content', models.TextField()),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sticky', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='product.categorymodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='product.tagsmodel')),
                ('blog_meta_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_meta_images', to='content.imagemodel')),
                ('blog_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_thumbnails', to='content.imagemodel')),
            ],
            options={
                'verbose_name': 'BlogModel',
                'verbose_name_plural': 'BlogModels',
                'db_table': 'Blog',
            },
        ),
    ]
