# Generated by Django 5.1.3 on 2025-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('product', '0002_categorymodel_tagsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='blog', to='product.tagsmodel'),
        ),
    ]
