# Generated by Django 5.1.3 on 2025-01-22 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_faqmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationdataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('refund', 'Refund'), ('coupon', 'Coupon')], max_length=255)),
            ],
            options={
                'verbose_name': 'NotificationdataModel',
                'verbose_name_plural': 'NotificationdataModels',
                'db_table': 'NotificationData',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('notifiable_type', models.CharField(max_length=255)),
                ('notifiable_id', models.IntegerField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.notificationdatamodel')),
            ],
            options={
                'verbose_name': 'NotificationModel',
                'verbose_name_plural': 'NotificationModels',
                'db_table': 'Notification',
            },
        ),
    ]
