# Generated by Django 5.1.3 on 2025-01-23 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='parent_category', to='product.categorymodel'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_icons', to='content.imagemodel'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_images', to='content.imagemodel'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.categorymodel'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('product', 'Product'), ('both', 'Both'), ('post', 'Post')], max_length=50),
        ),
    ]
