# Generated by Django 5.1.3 on 2025-01-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributemodel',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='attributemodel',
            name='attribute_value',
            field=models.ManyToManyField(blank=True, null=True, to='product.attributevaluemodel'),
        ),
    ]
