# Generated by Django 5.1.3 on 2025-01-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_descriptions_categorymodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='subcategories',
        ),
    ]
