# Generated by Django 5.1.3 on 2025-01-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_variationmodel_variation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareitemmodel',
            name='compare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_items', to='product.comparemodel'),
        ),
    ]
