# Generated by Django 5.1.3 on 2025-01-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tagsmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='shipping_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('on_backorder', 'On Backorder')], default='in_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple product'), ('variable', 'Product with variations'), ('grouped', 'Collection of products'), ('external', 'External product'), ('affiliate', 'Affiliate product'), ('virtual', 'Virtual product'), ('downloadable', 'Downloadable product')], max_length=100),
        ),
        migrations.AlterField(
            model_name='variationmodel',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('on_backorder', 'On Backorder')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='product',
        ),
    ]
