# Generated by Django 5.1.3 on 2025-01-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_attributemodel_attribute_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributemodel',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='attributevaluemodel',
            name='attribute_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.attributemodel'),
        ),
    ]
