# Generated by Django 5.1.3 on 2025-01-22 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_storemodel_taxmodel_variationmodel_productmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CompareModel',
                'verbose_name_plural': 'CompareModels',
                'db_table': 'Compare',
            },
        ),
        migrations.CreateModel(
            name='CompareitemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_items', to='product.productmodel')),
                ('compare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.comparemodel')),
            ],
            options={
                'verbose_name': 'CompareitemModel',
                'verbose_name_plural': 'CompareitemModels',
                'db_table': 'CompareItem',
            },
        ),
    ]
