# Generated by Django 5.1.3 on 2025-01-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('product', '0003_alter_compareitemmodel_compare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_galleries',
            field=models.ManyToManyField(blank=True, related_name='product_galleries', to='content.imagemodel'),
        ),
    ]
