# Generated by Django 5.1.3 on 2025-01-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_attributemodel_attribute_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevaluemodel',
            old_name='attribute_values',
            new_name='attribute',
        ),
    ]
