# Generated by Django 5.1.3 on 2025-01-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_attribute_values_attributevaluemodel_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevaluemodel',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attributemodel'),
        ),
    ]
