# Generated by Django 5.1.3 on 2025-01-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_attributevaluemodel_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevaluemodel',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.attributemodel'),
            preserve_default=False,
        ),
    ]
