# Generated by Django 5.1.3 on 2025-01-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentaccountmodel',
            old_name='user',
            new_name='consumer',
        ),
    ]
